app:
  name: Eatr

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN

logging:
  level:
    org.springframework.web: ERROR
    com.vincent.eatr: DEBUG
    
server:
  port: 8082